### ISSUE TITLE
Have a way to avoid repeating messages in multiple validators / colocate with schema definition

### ISSUE THREAD

**Issue by targos** [adonisjs/adonis-validation-provider#101]
## Why this feature is required (specific use-cases will be appreciated)?

To avoid having to repeat the same message if a specific validation rule is used in multiple validators in the app, there needs to be some way of colocating the message with the rule.
One way to do it would be to have a generic option available to all rules but am open to alternatives.

Example:
```ts
// In some file that exports reusable schemas
export const nameSchema = schema.string({ trim: true }, [
  // Matches any name except those containing characters not allowed in filenames on Windows.
  rules.regex(/^[^\\/:*?"<>|]+$/, { message: 'Name cannot contain special characters' }),
]);
```

For reference, in the `yup` library, the rules accept an optional `message` argument: https://github.com/jquense/yup#mixedrequiredmessage-string--function-schema

## Have you tried any other work arounds?

I haven't found any work around.

## Are you willing to work on it with little guidance?

Yes

**Comment by thetutlage** [comment]
Something I don't want to touch right now. Also, once we will have the translations package in place. We will read messages from translation files and inling them will be inefficient. For example

With dedicated messages object

```ts
public messages = intl.locale(ctx.locale).get('errors')
```

With inline messages

```ts
rules.regex(/^[^\\/:*?"<>|]+$/, { message: intl.locale(ctx.locale).get('errors.regex') }),
```

and then repeating it with each rule

**Comment by targos** [comment]
Okay, let's wait to see how it goes with the intl package 👍
