### ISSUE TITLE
AfterOrEqualTo and BeforeOrEqualTo rules to date schema

### ISSUE THREAD

**Issue by popovicieduard** [adonisjs/adonis-validation-provider#102]
## Why this feature is required (specific use-cases will be appreciated)?

Adding afterOrEqualTo and beforeOrEqualTo rules to date schema would be easier to read code-wise than using after or before rules in some use-cases, let's say you want to validate a date that is after today, including today, having to format the date to accomodate the after rule would be harder than using a new rule like afterOrEqualTo.
## Have you tried any other work arounds?

created custom rules
## Are you willing to work on it with little guidance?

Yes, going to create a PR if it makes sense to add such rules.

**Comment by thetutlage** [comment]
Go ahead!
