### ISSUE TITLE
Change Indicative configurations

### ISSUE THREAD

**Issue by macanhajc** [adonisjs/adonis-validation-provider#105]
There is a way to change the adonis indicative configurations ? 
I need to remove all body attributes that is not on the rules of my Validator, so I think it should be something like the `removeAdditional` of the [configurations](https://indicative.adonisjs.com/guides/master/configure). I cant find a way using like
```
const Validator = use('Validator'); 
Validator.configure({ removeAdditional: true });
```

I saw that [here](https://github.com/adonisjs/validator/blob/ed1bbeabe1bdcb53ce9d73a4155391c9809ec7fb/providers/ValidatorProvider.ts#L31) the `validator.configure` is set by getting the `validator` config from the `app.js` file, but even adding `validator: { removeAdditional: true }` I have no success

**Comment by TiagoGouvea** [comment]
I'm needing this as well. I didn't found a way to avoid not existing attributes to my validators, resulting in SQL error, when it tries to save an attribute that doesn't exist.
