### ISSUE TITLE
issue in rules.range in combination with refs and cacheKey

### ISSUE THREAD

**Issue by mastermunj** [adonisjs/adonis-validation-provider#106]
Hi,

While using `rules.range` with `refs` and `cacheKey`, the validation does not work properly.

## Package version
`@adonisjs/validator@8.2.0`

## Node.js and npm version
Node: 14.15.1
NPM: 6.14.9

## Sample Code (to reproduce the issue)
Run following commands in sequence and see the error message:

### Command 1
```
curl --location --request POST 'localhost:9000/limits' \
--header 'Content-Type: application/json' \
--data-raw '{
    "maximumLimit": 60000,
    "availableLimit": 90000
}'
```
#### Expected Output
```json
{
    "availableLimit": [
        "Available Limit should be between 0 to 60000"
    ]
}
```

### Command 2
```
curl --location --request POST 'localhost:9000/limits' \
--header 'Content-Type: application/json' \
--data-raw '{
    "maximumLimit": 80000,
    "availableLimit": 90000
}'
```
#### Expected Output
```json
{
    "availableLimit": [
        "Available Limit should be between 0 to 80000"
    ]
}
```
#### Actual Output
```json
{
    "availableLimit": [
        "Available Limit should be between 0 to 60000"
    ]
}
```

### Issue
The validation still runs with maximumLimit as 60000 rather than 80000 which is the update value passed.

## Cache
When cache is disabled, by commenting this [line](https://github.com/mastermunj/adonis-range-issue/blob/main/app/Validators/LimitValidator.ts#L18), the validation works as expected.

## BONUS (a sample repo to reproduce the issue)
https://github.com/mastermunj/adonis-range-issue

**Comment by thetutlage** [comment]
The `refs` are used incorrectly. You don't have to read the value property from it. It should be `this.refs.maximumLimit`

**Comment by thetutlage** [comment]
Also, I see that the `range` method doesn't accept the range at all. Is range dynamic in your case, meaning it changes depending upon the request?

**Comment by mastermunj** [comment]
> The `refs` are used incorrectly. You don't have to read the value property from it. It should be `this.refs.maximumLimit`

If I use `this.refs.maximumLimit`, I get following typescript error.
```
Argument of type 'SchemaRef<unknown>' is not assignable to parameter of type 'number'.
```


> Also, I see that the `range` method doesn't accept the range at all. Is range dynamic in your case, meaning it changes depending upon the request?

Yes, the range changes depending on the current value passed for `maximumLimit`.

**Comment by mastermunj** [comment]
Hi @thetutlage I am facing similar issue with maxLength rule as well. There also I need to pass length based on the value of another parameter.

Any suggestions for a workaround for both range and maxLength?

**Comment by thetutlage** [comment]
For now turning of the schema caching is the way to go. I will add support for using `refs` for the maxLength argument as well.

**Comment by thetutlage** [comment]
Will work on it

**Comment by mastermunj** [comment]
Hi @thetutlage Is this still part of plan? This one is closed of no-activity so might get missed.
