### ISSUE TITLE
Validator not responding with error when fails

### ISSUE THREAD

**Issue by JaconsMorais** [adonisjs/adonis-validation-provider#108]
Hello guys, I'm using Validator to validate some params in request url using example provided in [docs](https://adonisjs.com/docs/4.1/validator#_custom_data_object)
data:

```
get data() {
    try {
      const requestBody = this.ctx.request.all()
      return { ...requestBody, uid: this.ctx.params.id}
    } catch (error) {
      console.log(error.message)
    }
  }
```

Then, in rules I added:

```
get rules() {
    return {
      field: ['required', 'string', rule('in', ['cpf', 'uid', 'code'])],
      uid: [
        'required',
        rule('regex', new RegExp('^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$')),
      ]
    }
  }
```

But, the problem is, validation do not stop request life cycle and dont return any error, even when params has incorrect values.
See my route:

`Route.get('/students/:id/:field', 'StudentController.show').validator('v1/student/show')`

**Comment by thetutlage** [comment]
Will need more info. Like the data you are sending and also the complete code for the validator class. Is the validator stored inside the `app/validators/v1/student/show.js` file?

**Comment by JaconsMorais** [comment]
Hi, thanks for your reply.

here the validator code stored in /app/Validators/v1/student/show.js

```
'use strict'

const TABLE_NAME = 'students'
const { rule, formatters, configure } = use('Validator')

class v1StudentShow {

  get rules() {
    return {
      field: ['string', rule('in', ['cpf', 'uid', 'code'])],
    }
  }

  get messages() {
    return {
      'field.required': 'Você precisa selecionar qual campo deseja buscar.',
      'field.string': 'Campo informado inválido.',
      'field.in': 'Busca realizada com termos incorretos.',
    }
  }

  get data() {
    try {
      const requestBody = this.ctx.request.all()
      const data = {}

      if ('field' in this.ctx.params) data['field'] = this.ctx.params.field
      console.log(data)

      return { ...requestBody, ...data }
    } catch (error) {
      console.log(error.message)
    }
  }

  async authorize() {
    const authenticatedUser = this.ctx.auth.user

    await authenticatedUser.load('roles')

    const authorizations = (authenticatedUser.toJSON()).roles.authorizations

    if (authorizations != null
      && TABLE_NAME in authorizations
      && authorizations[TABLE_NAME].includes('r'))
      return true



    this.ctx.response.unauthorized('Você não possui permissões para visualizar este aluno.')
    return false;
  }
}

module.exports = v1StudentShow
```

When I request using valid url, its all ok
![image](https://user-images.githubusercontent.com/6156243/108087742-1ced3600-704e-11eb-8877-0e3dbb662e2e.png)

But, when I input invalid url params, validator does not thrown any errors and the controller is called, then the error ocurs in database query.

![image](https://user-images.githubusercontent.com/6156243/108087896-43ab6c80-704e-11eb-9c1d-cf419c1339c7.png)

My request url is /students/:id/:field

when field is one column in my table and id is value to be searched in that column, but field needs to be only 'cpf' or 'uid' or 'code'

**Comment by JaconsMorais** [comment]
@thetutlage check route:list output for students resource:

![image](https://user-images.githubusercontent.com/6156243/108263947-446efc00-713d-11eb-9bb4-585bdd531180.png)

**Comment by JaconsMorais** [comment]
@thetutlage any update on this?
