### ISSUE TITLE
Cannot find module '@adonisjs/validator/providers/ValidatorProvider'

### ISSUE THREAD

**Issue by eazzyLEE** [adonisjs/adonis-validation-provider#110]
## Package version
4.1.0

## Node.js and npm version
v14.15.0 and 6.14.8

## Sample Code (to reproduce the issue)
run `adonis new <project_name> --api-only`

install/setup adonis validator by following the documentation: running `adonis install @adonisjs/validator` and adding `@adonisjs/validator/providers/ValidatorProvider` to the providers array in start/app.js

the following error is thrown when you try to start the app:

> Error: Cannot find module '@adonisjs/validator/providers/ValidatorProvider'
>Require stack:

> - /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/node_modules/require-stack/src/index.js
> - /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/node_modules/require-stack/index.js
> - /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/node_modules/@adonisjs/fold/src/Ioc/index.js
> - /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/node_modules/@adonisjs/fold/index.js
> - /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/ace
> - /usr/local/lib/node_modules/@adonisjs/cli/index.js
> 
> 
> 1 requireStack
>   /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/node_modules/require-stack/src/index.js:44
> 
> 2 anonymous
>   /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/node_modules/@adonisjs/fold/src/Registrar/index.js:104
> 
> 3 arrayMap
>   /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/node_modules/lodash/lodash.js:653
> 
> 4 Function.map
>   /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/node_modules/lodash/lodash.js:9622
> 
> 5 interceptor
>   /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/node_modules/lodash/lodash.js:17094
> 
> 6 thru
>   /Users/xxxxx/Documents/Personal/payment-services/xxxxx-xxxxx/node_modules/lodash/lodash.js:8859

When I checked the `@adonisjs/validator` directory in **node_modules**, the providers folder was missing.

this has to be a very recent change, because nothing like this is mentioned in the docs

**Comment by eazzyLEE** [comment]
@thetutlage can you help look into this.. setting up @adonisjs/validator is throwing this error

**Comment by alessandroprudencio** [comment]
@eazzyLEE I have the same problem.

**Comment by blackxthink** [comment]
Same issue here

**Comment by Shiba-Kar** [comment]
``adonis new <project_name> --api-only``
```

Error: Cannot find module '@adonisjs/validator/providers/ValidatorProvider'
Require stack:
- C:\Programming\Node.js\blog-api\node_modules\require-stack\src\index.js
- C:\Programming\Node.js\blog-api\node_modules\require-stack\index.js
- C:\Programming\Node.js\blog-api\node_modules\@adonisjs\fold\src\Ioc\index.js
- C:\Programming\Node.js\blog-api\node_modules\@adonisjs\fold\index.js
- C:\Programming\Node.js\blog-api\server.js


1 requireStack
  C:\Programming\Node.js\blog-api\node_modules\require-stack\src\index.js:44

2 anonymous
  C:\Programming\Node.js\blog-api\node_modules\@adonisjs\fold\src\Registrar\index.js:104

3 arrayMap
  C:\Programming\Node.js\blog-api\node_modules\lodash\lodash.js:653

4 Function.map
  C:\Programming\Node.js\blog-api\node_modules\lodash\lodash.js:9622

5 interceptor
  C:\Programming\Node.js\blog-api\node_modules\lodash\lodash.js:17094

6 thru
  C:\Programming\Node.js\blog-api\node_modules\lodash\lodash.js:8859
```

**Comment by Shiba-Kar** [comment]
```"@adonisjs/validator": "^5.1.0",```
This works for me

**Comment by alessandroprudencio** [comment]
> "@adonisjs/validator": "^5.1.0",

@Shiba-Kar  well, it really works

**Comment by Gittenger** [comment]
> `"@adonisjs/validator": "^5.1.0",`
> This works for me

I'm having the same issue, hopefully they get it figured out soon.
But using an older version of validator like this worked for me too. :)

**Comment by AmosKorir** [comment]
Same issue with "@adonisjs/validator": "^10.0.0",

**Comment by thetutlage** [comment]
The latest version of the validator is meant to be used with the v5. Please install the package with the `legacy` tag to make it work with v4.

```sh
npm i @adonisjs/validator@legacy
```

Closing the issue, since no action is required on our end

**Comment by aryanicosa** [comment]
> ```shell
> npm i @adonisjs/validator@legacy
> ```

thanks dude, it's work!

**Comment by shobhit-goomood** [comment]
`npm i @adonisjs/validator@legacy` worked for me. 👍 

Thanks

**Comment by Osomhe1** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/64287450/125191974-2c5b5e80-e23d-11eb-9631-659a4adb9285.png)
 having same issue  npm i @adonisjs/validator@legacy did not work for me, what do I do please?

**Comment by graceEjegwa** [comment]
I'm having the same issue and using npm i @adonisjs/validator@legacy did not work for me, has this been resolved?
