### ISSUE TITLE
Unique validation at update time

### ISSUE THREAD

**Issue by Areebsofyrus** [adonisjs/adonis-validation-provider#112]
get rules() {
    const companyId = this.ctx.params.id;
    return {
      // validation rules
      name: [
        rule("required"),
        rule("max", 30),
        rule("regex", /^([a-zA-Z0-9 ]+(\.)?([a-zA-Z0-9 ]+)?)+$/u),
        rule("unique","companies",`id,${companyId}`),
      ],
      email: `required|unique:companies,email,id,${companyId}|email`,
      contact: `required|integer|max:15|unique:companies,contact,id,${companyId}`,
    };
  }

Here as you can see i have to update company details,and i have to use regex for validation too so i can't write validation in normal way (without using array and rule method i.e unique:companies,name,${companyId}).
I have to use it in above manner but unique inside rule method not accepting ignore row field as we can do it in normal way.So what should be the correct syntax.

Either tell me how to write above validation correctly or how to use regex properly without using rule method 

Will be thankful for help

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
