### ISSUE TITLE
file is not defined as a validation rule

### ISSUE THREAD

**Issue by Areebsofyrus** [adonisjs/adonis-validation-provider#113]
'use strict'

class StoreUser {
  get rules () {
    return {
      avatar: 'file|file_ext:png,jpg|file_size:2mb|file_types:image'
    }
  }
}

module.exports = StoreUser

I have tried the above code for route validation of file but it is throwing the error as:
        "message": "file is not defined as a validation rule",
        "field": "image",
        "validation": "ENGINE_EXCEPTION"

Please help me out how can i validate file before reaching the controllers.Any help will be much appreciated

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
