### ISSUE TITLE
Validation convert empty string to undefined

### ISSUE THREAD

**Issue by rodrigorz** [adonisjs/adonis-validation-provider#114]
## Package version
- @adonisjs/assembler: ^5.3.0
- @adonisjs/auth: ^8.0.4
- @adonisjs/core: ^5.1.7
- @adonisjs/lucid: ^14.1.0
- @adonisjs/mail: ^7.1.1
- @adonisjs/repl: ^3.1.2
- @adonisjs/view: ^6.0.2

## Node.js and npm version
- node: v14.16.0
- npm: 6.14.11

## Sample Code (to reproduce the issue)
The example below shows a request sending data via json.
```js
// validation schema
class MyValidator {
  constructor(protected ctx: HttpContextContract) {}

  public schema = schema.create({
    group: schema.string.optional({ trim: true }),
  });
}

// Controller update method
public async update(ctx: HttpContextContract) {
  const { request } = ctx;

  console.log({
    before: request.input('group'),  // output => before: ''
  });

  const { group } = await request.validate(MyValidator);

  console.log({
    after: group,  // output => after: undefined
  });
}
```
So, if `group` already has a saved value and I want to clear that value, the `model.merge` method will not change the `group` because it is undefined.

The validation should keep the empty string? Or the `bodyparser json settings` also needs `convertEmptyStringsToNull`? Or am I doing something wrong?

**Comment by rodrigorz** [comment]
I just tried to execute the same example but sending via FormData with `convertEmptyStringsToNull: true`. And I have the same problem.
```js
// Controller update method
public async update(ctx: HttpContextContract) {
  const { request } = ctx;

  console.log({
    before: request.input('group'),  // output => before: null
  });

  const { group } = await request.validate(MyValidator); // the request data is a FormData

  console.log({
    after: group,  // output => after: undefined
  });
}
```

**Comment by rodrigorz** [comment]
@thetutlage could you help me?

**Comment by rodrigorz** [comment]
As a workaround, I created a custom rule `setDefault` that takes the default value as a parameter and `mutate` the value if necessary.

**Comment by thetutlage** [comment]
Validator needs improvement in this area. I will be working on it this week

**Comment by rodrigorz** [comment]
Hi, any progress? I'm a little looking forward to it 😆.

I have an idea, maybe there might be an option in each `schema type .optional()` to set the default value;

Ex:
```js
schema.string.optional({ trim: true }) // if value is undefined, keep undefined
schema.string.optional({ trim: true, default: null }) // if value is undefined set null
schema.string.optional({ trim: true, default: 'my-value' }) // if value is undefined set 'my-value' | if value is null, keep null (only set default if value is not sent)
```
And `default` will accept `schema type  | null` values.
schema.string -> string | null
schema.number -> number | null
schema.array -> array | null
... all schema types

Would that work?

**Comment by rodrigorz** [comment]
Hi, I updated the core package to version 5.1.11 and my custom rule `setDefault` no longer changes the value of the field, it looks like the `mutate` function doesn't do its job.

Can you see that too?

OBS: In version 5.1.7 (or 8) mutate was working.

Here is the rule code. (This code is executed, i can debug or log its contents, but mutate seems to do nothing)
```ts
import { validator } from '@ioc:Adonis/Core/Validator';
import { types, string } from '@ioc:Adonis/Core/Helpers';

validator.rule(
  'setDefault',
  (value, [defaultValue, denyZero], { mutate }) => {
    const type = types.lookup(value);

    switch (type) {
      case 'string':
        if (string.isEmpty(value)) {
          mutate(defaultValue);
        }
        break;
      case 'number':
        if (isNaN(value) || (value === 0 && denyZero)) {
          mutate(defaultValue);
        }
        break;
      default:
        if (!value) {
          mutate(defaultValue);
        }
        break;
    }
  },
  () => ({
    allowUndefineds: true,
  })
);
```

**Comment by rodrigorz** [comment]
HI, any progress with this feat?

**Comment by sockenklaus** [comment]
Hi I'd like to push this issue. The current behaviour (validating empty strings to undefined) seems pretty off since "" is an intentional value and should be treated a such.

I'd like to try solving this issue but i'm really lacking the skill :(

**Comment by Alyxsqrd** [comment]
I'm also interested in seeing support for this added. I find it pretty odd how using `schema.string({trim: true})` doesn't return undefined on empty/whitespace only strings. I also noticed that for rules such as `rules.minLength(1)`, it seems like the input length is being checked **before** it's trimmed. 🤔

Hopefully this confusing functionality is fixed by default, or at least, add a validator config option to support this such as {undefinedOnWhitespace: true} 👍

**Comment by rodrigorz** [comment]
The issue seems to be solved on this [discussion](https://github.com/adonisjs/core/discussions/1978).

I will close this issue if it works.
