### ISSUE TITLE
Validation Not Working

### ISSUE THREAD

**Issue by manoj-manoharan-backup-old** [adonisjs/adonis-validation-provider#12]
I tried sending nothing in request but validation is not failing

```js
/** Validate If NOT NULL [ title, content, tags ] */
 let title = request.input("title");
 let content = request.input("content");
 let tags = request.input("tags");

    const validation = yield Validator.validate(
      request.all(),
      TextContent.rules,
      "All fields Required"
    );

    if (validation.fails()) {
      response.json(validation.messages());
      return;
    }
    response.json({
      success: true,
      message: "Post Added"
    });
```

**Comment by thetutlage** [comment]
Mind sharing the rules?

**Comment by manoj-manoharan-backup-old** [comment]
`static get rules() {
    return {
      title: 'required',
      content: 'required'
    }
  }`

**Comment by thetutlage** [comment]
And what is the output of `request.all()`

**Comment by manoj-manoharan-backup-old** [comment]
It's empty

`{}`

**Comment by thetutlage** [comment]
It needs to have the keys for `title` and `content` to be validated. Rules are applied on data and empty object has no data

**Comment by manoj-manoharan-backup-old** [comment]
Tried that too now

`{ title: '', content: '', tags: '' }`

but still not working

**Comment by thetutlage** [comment]
What is the 3rd argument with a string `"All fields Required"`. Messages needs to be an object http://indicative.adonisjs.com/#indicative-basics-custom-messages

**Comment by manoj-manoharan-backup-old** [comment]
Tried that too now, Updated code

` const messages = {
      required: 'This field is required to complete the registration process.'
    }; `
` const validation = yield Validator.validate(
      request.only('title','content'),
      TextContent.rules,
      messages
    );
`

**Comment by thetutlage** [comment]
Not sure, works for me. Here is a sample repo with code https://github.com/thetutlage/validation-issue-12

**Comment by manoj-manoharan-backup-old** [comment]
That's odd :( Validation caused problem in my old project too, so i thought it was some bug in version but now i'm using latest version. Not sure why is this happening. 

Maybe i didn't properly configure it?
1. installed adonis-validator-provider
2. added in Aliases and Providers list

that's it right?

**Comment by thetutlage** [comment]
Yes, otherwise it will throw an exception. You can double check your code against the created sample repo.

**Comment by manoj-manoharan-backup-old** [comment]
Its working on the Sample repo, seems to be problem with my configuration. Thank you for your time :1st_place_medal: :+1:
