### ISSUE TITLE
Allow create custom validations

### ISSUE THREAD

**Issue by sandhilt** [adonisjs/adonis-validation-provider#122]
## Why this feature is required (specific use-cases will be appreciated)?
Some rules is very specify from business and we need do a validation outside from framework of validation.
An example for this, Adonis Indicative have rule's integer and Adonis v5 don't.

## Have you tried any other work arounds?
Adonis Indicative 

## Are you willing to work on it with little guidance?
Yes

**Comment by thetutlage** [comment]
Documented https://docs.adonisjs.com/guides/validator/custom-rules.

Closing for now. Feel free to reopen the issue if the docs doesn't fix your issue
