### ISSUE TITLE
![Screenshot (13)](https://user-images.githubusercontent.com/64287450/125191974-2c5b5e80-e23d-11eb-9631-659a4adb9285.png)

### ISSUE THREAD

**Issue by graceEjegwa** [adonisjs/adonis-validation-provider#123]
![Screenshot (13)](https://user-images.githubusercontent.com/64287450/125191974-2c5b5e80-e23d-11eb-9631-659a4adb9285.png)
 having same issue  npm i @adonisjs/validator@legacy did not work for me, what do I do please?

_Originally posted by @Osomhe1 in https://github.com/adonisjs/validator/issues/110#issuecomment-877777921_

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
