### ISSUE TITLE
Is there way to use validators without http request?

### ISSUE THREAD

**Issue by Uttam-EWW** [adonisjs/adonis-validation-provider#130]
So basically what i want to achieve is  to validate other data by using this validator's functionalities. So is there anyway to do it?

**Comment by thetutlage** [comment]
Its covered in the docs here. https://docs.adonisjs.com/guides/validator/introduction#standalone-validator-usage

**Comment by Uttam-EWW** [comment]
> Its covered in the docs here. https://docs.adonisjs.com/guides/validator/introduction#standalone-validator-usage

Thank you so much.

**Comment by thetutlage** [comment]
Closing. In the future you can use the discussions forum to ask your questions http://github.com/adonisjs/core/discussions

We use the issues tracker for just managing feature requests and bugs
