### ISSUE TITLE
Bug with Validator: rules aren't applied after trim

### ISSUE THREAD

**Issue by bnoufel** [adonisjs/adonis-validation-provider#143]
## Prerequisites

I found a bug on Validator that occurs when I create a schema validator to add data :
If on entry "name" I put only spaces (like `      `), the rules are not applied after trim, and gives an empty string (`{name: ""}`) rather than an invalid warning.

## Package version
5.5.0

## Node.js and npm version
Node: 17.5.0
npm: 8.4.1

## Sample Code (to reproduce the issue)
schema code:
```ts
  public schema = schema.create({
    name: schema.string(
      {
        trim: true,
        escape: true,
      },
      [rules.minLength(2), rules.maxLength(64)]
    ),
  })
```

Thanks 🎉

**Comment by RomainLanz** [comment]
Hey @bnoufel! 👋🏻 

This is something we discussed many times in the core team and I am not sure what the best approach would be.
Do you have any examples of how it is handled in other frameworks?

**Comment by bnoufel** [comment]
So here's how SF is handling this issue :
```php
    #[ORM\Column(type: 'string', length: 255)]
    #[Assert\Length(min: 2, max: 255)]
    #[Assert\NotBlank(normalizer: 'trim')]
```

In this case, it'll be correctly be trimed (and it will not accept an empty string as entry).
In order to repeat the same behaviour in Adonis, you'll have to do it this way by adding a `required` rules that will check the trimed string at the end :

```ts
    name: schema.string(
      {
        trim: true,
        escape: true,
      },
      [rules.minLength(2), rules.maxLength(64), rules.required()]
    ),
```

In my opinion, the best approach would be to add a blank option to the previous code instead of the `required` rules, in order to reproduce almost the same behaviour as SF but with more flexibility :

```ts
    name: schema.string(
      {
        trim: true,
        escape: true,
        blank: false
      },
      [rules.minLength(2), rules.maxLength(64)]
    ),
```

However, we'll still have a major issue (either with SF or Adonis) in a case like  
![unknown](https://user-images.githubusercontent.com/6586577/158080804-9f2c15c6-cda6-432f-a165-ff79fa477ec0.png)
: because the validation of minLength is done before the trim, name will be valid and be returned as {name: "f"}.
I understand the logic behind this specific validation, it's just that having to double-check in some cases is kinda unfortunate !

**Comment by thetutlage** [comment]
I have added two new rules (`escape`, `trim`) to the validator. Now, instead of using them as options, you can use the rules directly.

```ts
name: schema.string([
  rules.minLength(2),
  rules.maxLength(64),
  rules.trim(),
])
```

Since rules are applied in the order they are defined, you can self control the execution flow.

PS: The rules will be available after next release of validator and core.

Commit: https://github.com/adonisjs/validator/commit/7a0402ec02f5cd6da5424f42aed9f015b4597391

**Comment by bnoufel** [comment]
Thx !
i try this asap 🎉
