### ISSUE TITLE
Schema options after rules

### ISSUE THREAD

**Issue by DZ8540** [adonisjs/adonis-validation-provider#145]
## Why this feature is required (specific use-cases will be appreciated)?
Most AdonisJS users happen to even add trim option when create string schema validator, if passing rules to this string validator. It is not comfortable!

example:
![изображение](https://user-images.githubusercontent.com/50152205/161020845-53786bc5-8e57-4ad8-961a-ffbda3c62797.png)

It would be great if the options were after the rules, then all users wouldn't have to passing trim option for string validator every time. 

As a suggestion, make a escape option to false a default, because, i think, users do not use this a lot.
If users need to pass true to the escape parameter, they will simply pass it after the rules.

You can also make a vote is it worth it to do so, suddenly I'm wrong.

## Have you tried any other work arounds?
No, I haven't found any other work arounds.

## Are you willing to work on it with little guidance?
I'm ready to do whatever is necessary to achieve this goal.

**Comment by thetutlage** [comment]
Going to be a breaking change and cannot be shipped until AdonisJS 6.0

**Comment by thetutlage** [comment]
This [commit](https://github.com/adonisjs/validator/commit/7a0402ec02f5cd6da5424f42aed9f015b4597391#diff-662b765160dd0104d1e865cea89351b2611b996f1762f6ef3081555275665c80R288) makes the first argument to accept both the `options` or an array of `rules`. 

After the next release, you can simplify your code as follows.

```ts
schema.string([
  rules.unique(),
  rules.minLength()
])
```
