### ISSUE TITLE
Date - Custom Message

### ISSUE THREAD

**Issue by ruanitto** [adonisjs/adonis-validation-provider#146]
I need a custom message on validator for data fields to show the date format, but the options passed to the message string is undefined

## Package version
12.2.3

## Node.js and npm version
node: 14
npm: 6

## Sample Code (to reproduce the issue)
```JS
const dateField = await validator.validate({
        schema: schema.create({
          startDate: schema.date({ format: 'yyyy-MM-dd' })
        }),
        messages: {
          'date.format': '{{ field }} must be formatted as {{ format }}',
        },
        data: {
          startDate: 'anyValue'
        }
   })
```
When the error ocurrs, the options is caming undefined:

```JS
{
 ...
 messages: { startDate: [ 'startDate must be formatted as undefined' ] }
 ...
}
```

**Comment by thetutlage** [comment]
<img width="733" alt="CleanShot 2022-04-05 at 16 30 35@2x" src="https://user-images.githubusercontent.com/1706381/161739908-070240b5-d2df-4ba8-b8d7-6b522dbb84a2.png">

Seems like a typo in the code example. It should be `options.format`.

**Comment by ruanitto** [comment]
I also tried it before. but the same error occurs.
Later I'll take a look at the validator's source code and see if I can find the fix, or where I'm going wrong.
Apparently the options object arrives empty

![Screenshot_26](https://user-images.githubusercontent.com/13773521/161771641-f8db7c2d-578e-4316-a8af-df101b444e71.png)
.

**Comment by thetutlage** [comment]
Seems like a bug in the code. Fixed in https://github.com/adonisjs/validator/commit/f60dea0f88bcc3bb8955ec8c8443a6068fcde1d1

Will be released soon
