### ISSUE TITLE
`minLength` rule doesn't respect `trim` rule

### ISSUE THREAD

**Issue by cawa-93** [adonisjs/adonis-validation-provider#147]
## Package version
"@adonisjs/core": "5.7.6",

## Node.js and npm version
 node v16.14.0
 npm 8.3.1

## Sample Code (to reproduce the issue)
```ts
await validator.validate({
  schema: schema.create({
    text: schema.string([
      rules.trim(),
      rules.minLength(1),
    ]),
  }),
  data: {
    text: ' ',
  },
})
```
Validation is not expected to pass, but it is passing

**Comment by cawa-93** [comment]
Here is

https://github.com/adonisjs/validator/blob/2d63698452957fd946c73862b9fbf9b4c633eb51/src/Validations/string-and-array/minLength.ts#L40

For some reason rule check `originalValue` but not actual `value`

**Comment by thetutlage** [comment]
Thanks for reporting.

Yup. That was required earlier when `trim` was just an option and not the rule itself. But, we should now rely on the mutated value.
