### ISSUE TITLE
Integration with Adonis Antl

### ISSUE THREAD

**Issue by mertindervish** [adonisjs/adonis-validation-provider#16]
I'm looking for a way to internationalize my validations. I've kinda solved the problem by generating messages using rules like in the code below:

```javascript
const rules = {
  'name': 'required'
}

const messages = Utilities.antlValidationMessages(rules)

const validation = yield Validator.validate(data, rules, messages)
```

It works but I'm wondering if there is a more elegant solution.

**Comment by thetutlage** [comment]
Validator does not offer any direct way of pulling messages from locales. This is in my pipeline and I will working on it in the next release.

Keeping the issue open so that it stays in my mind

**Comment by thetutlage** [comment]
Received another question on same and realized the following should work.

```js
const messages = {
    'username.required': function () {
        return Antl.formatMessage('username.required')
    }
}

Validator.validate(data, rules, messages)
```

**Comment by mertindervish** [comment]
I mean something similar to Laravel's way. In Laravel all you have to do is to create a `validation.php` file and fill your translations. Then they are used in every validation (unless you give mesaages arguments ofc). Same is for attributes' translations. Check out Laravel's docs https://laravel.com/docs/5.4/validation#custom-error-messages

**Comment by thetutlage** [comment]
I shared that as a work around not as a solution, wait until I work on better integration

**Comment by mertindervish** [comment]
What is the difference between this

```javascript
const messages = {
    'username.required': function () {
        return Antl.formatMessage('username.required')
    }
}

Validator.validate(data, rules, messages)
```

and that?

```javascript
const messages = {
    'username.required': Antl.formatMessage('username.required')
}

Validator.validate(data, rules, messages)
```

I don't see any benefit of a callback for a validation message. Am I missing something?

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by oliveiradouglas** [comment]
@thetutlage has the definitive solution to this problem?
