### ISSUE TITLE
Issue in document

### ISSUE THREAD

**Issue by hsharma1996** [adonisjs/adonis-validation-provider#160]
## Prerequisites

Change **The trim is sanitization rule to trim all the whitespaces from the left and the trim of the string** to **The trim is sanitization rule to trim all the whitespaces from the left and the right of the string.** on docs/reference/validator/rules/trim

**Comment by RomainLanz** [comment]
Hey! 👋 

Your issue does not follow our guidelines.

1. Make sure you only report bugs or submit feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience, not just you.

If you are not submitting a bug and neither a feature request, then please use the [Github Discussion](https://github.com/adonisjs/core/discussions)


**In any case, issues that are not descriptive enough will be closed. Please respect our time.**
