### ISSUE TITLE
Unique validation rule should support an ignore row clause using a field/value pair

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/adonis-validation-provider#2]
Unique validation rule must support a field/value pair to ignore a row when doing the validation. It will be helpful when trying to update the field.
## Current Signature

``` javascript
const rules = {
    email: 'unique:users,email'
}
```

Now when trying to update the user with the payload that has the same email address, will cause a unique validation failure, since this email has already been taken.

What we need is a way to ignore the current user by accepting another parameter that will have add the ignore clause to the unique validation.
## New Signature

Here `id,1` is a way to tell the unique validator, to ignore the row where `id=1`

``` javascript
const rules = {
    email: 'unique:users,email,id,1'
}
```
## Usage when updating logged in user profile

When trying to update profile of a logged in user, you are likely going to have the logged in user id.
#### app/Model/User

``` javascript
class User extends Lucid {

  static rules (userId) {
     return {
        email: `unique:users,email,id,${userId}`
     }
  }

}
```

Now when trying to validate the user input, you can fetch the rules like the following example
#### app/Http/Controllers/UserController

``` javascript
class UserController {

  * update (request, response) {
       const rules = User.rules(request.currentUser.id)
       yield Validator.validate(request.all(), rules)
   }

}
```
## Note:

I am open for more suggestions on the same.

**Comment by bitkidd** [comment]
Looks legit, but makes rules a bit complex, why not ignore row on update by default and add an option to validate & validateAll like this:

```
yield Validator.validate(request.all(), rules, {id: 1})
```

**Comment by thetutlage** [comment]
@keeross Ignoring part of rules shouldn't be the validators job, in ideal world `validator` has no idea what is a`create` or an `update`.

If you pass `{id: 1}`, how are you expecting to consume it back in your rules?

**Comment by bitkidd** [comment]
Basically, keeping validator modular is better, that's true. Maybe it is better to use a pipe symbol in place of comma, kinda `unique:users,email | ignore:id,1`, so it will be a bit more verbose

**Comment by thetutlage** [comment]
@keeross `|` is used to define multiple rules. For example `required|email` and making 2 rules work to validate a single piece of data together is not practical. :smile:

**Comment by thetutlage** [comment]
This is been released a while ago. Closing the issue 😄

**Comment by lmj0011** [comment]
>This is been released a while ago. Closing the issue :smile:

and yet, it's not updated in the docs
http://indicative.adonisjs.com/#indicative-schema-rules

**Comment by lmj0011** [comment]
needs documentation

**Comment by pedzed** [comment]
It does not seem to work. @thetutlage which commit resolved this issue?

**Comment by thetutlage** [comment]
@lmj0011 Why the changes related to this repo has to be documented in Indicative?
The `unique` rule is solely part of the adonis-validator and is documented here https://adonisjs.com/docs/4.1/validator#_custom_rules

**Comment by lmj0011** [comment]
Disregard my comments, in all Adonis related projects. I'll moved on from Adonis

**Comment by pedzed** [comment]
@lmj0011 That's not how open source works. If you want to opt out from notifications, you can unsubscribe, like in the image here:

![GitHub unsubscribe](https://user-images.githubusercontent.com/8146593/41228448-b1c186b8-6d78-11e8-81a7-107745fcd28e.png)

> It does not seem to work. @thetutlage which commit resolved this issue?

Apparently I wrote `unique:users,email,${userId}` rather than `unique:users,email,id,${userId}`. Now it works.

**Comment by thetutlage** [comment]
Yup it has to be `unique:users,email,id,${userId}`. Since you have to tell which column to ignore. 

The rule is added by `adonis-lucid`. You can see the implementation here https://github.com/adonisjs/adonis-lucid/blob/develop/src/Validator/index.js

**Comment by mukhsin** [comment]
Hi, I'm new to adonisjs
I have followed the instructions here
[https://github.com/adonisjs/adonis-lucid/blob/develop/src/Validator/index.js](https://github.com/adonisjs/adonis-lucid/blob/develop/src/Validator/index.js)

In development mode it works fine, I tested in postman
I have issue in test mode
It fails on ignoring the row

Here is my rule
![screenshot from 2018-06-13 11-59-42](https://user-images.githubusercontent.com/9584947/41331290-7f61ff32-6f02-11e8-944a-56c5ec100ec7.png)

This is the test
![screenshot from 2018-06-13 12-00-56](https://user-images.githubusercontent.com/9584947/41331295-931fb1c2-6f02-11e8-9a5c-0242b7ff435c.png)

This is what I got from postman (on development mode)
![screenshot from 2018-06-13 12-02-07](https://user-images.githubusercontent.com/9584947/41331308-a29de010-6f02-11e8-8eb9-64df3ca87ce2.png)

This is what I got from terminal (on test mode)
![screenshot from 2018-06-13 12-04-27](https://user-images.githubusercontent.com/9584947/41331311-acc01586-6f02-11e8-9148-387faee3d921.png)

Anyone can help me?
Thanks

**Comment by RomainLanz** [comment]
Hey @mukhsin!

Please, use the forum to ask this kind of question.

**Comment by YuriFontella** [comment]
Is there a simple way to make the unique validation rule defining a scope?

pages
number | chapter_id
1             1
1             2

I couldn't insert two identical pages for the same chapter, but for a different chapter key, yes.

Today ignoreField and IgnoreValue it puts a not in the query
'select * from "pages" where "number" =? and not "chapter_id" =? '

The idea would be just the opposite:
'select * from "pages" where "number" =? and "chapter_id" =? '

number: `required|unique:pages,number|scope:chapter_id,${chapterId}`

An example used in rails:
validates_uniqueness_of: number, scope: :chapter_id

Thanks
