### ISSUE TITLE
Rules format & Errors methods

### ISSUE THREAD

**Issue by duyluonglc** [adonisjs/adonis-validation-provider#21]
@thetutlage
I find the validator package with rules format and the methods are similar to Laravel validator
https://github.com/skaterdav85/validatorjs
How about if this provider has rules as object and the methods like this:
```js
// rules
var nested = {
  name: 'required',
  bio: {
    age: 'min:18',
    education: {
      primary: 'string',
      secondary: 'string'
    }
  }
};
// OR
var flattened = {
  'name': 'required',
  'bio.age': 'min:18'
  'bio.education.primary': 'string',
  'bio.education.secondary': 'string'
};

//methods:
var validation = new Validator(input, rules);
validation.errors.first('email'); // returns first error message for email attribute
validator.errors.get('email'); // returns an array of error messages for the email attribute
```
Sorry if you don't like this

**Comment by thetutlage** [comment]
So this becomes helpful when are inside some view layer, where you want to show certain messages next to the actual field.

In that case, the template engine can have methods, which pulls the right error messages.

I don't think the validator itself needs these methods
