### ISSUE TITLE
SQL Error using unique rule

### ISSUE THREAD

**Issue by seanc** [adonisjs/adonis-validation-provider#24]
It appears that the `unique` rule is not selecting any tables and causing an SQL error. I've tried providing it as an extra argument like `unique:users` with no results.

Here is the error:
```json
            "field": "email",
            "validation": "unique",
            "message": {
                "code": "ER_PARSE_ERROR",
                "errno": 1064,
                "sqlMessage": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where `email` = 'hello@imsean.me'' at line 1",
                "sqlState": "42000",
                "index": 0,
                "sql": "select * where `email` = 'hello@imsean.me'"
            }
```

I'm using adonis v4 as well.

**Comment by thetutlage** [comment]
You also have to define the `table` and field to be used for making the SQL query, so it should be.

```
email: 'unique:users,email'
```

**Comment by seanc** [comment]
Huh, I tried that as well and it didn't work. Tried it again though and it appears to work. I probably missed something haha.
