### ISSUE TITLE
Running validations after authorization

### ISSUE THREAD

**Issue by simontong** [adonisjs/adonis-validation-provider#25]
It seems a bit pointless to run validation checks if the authorization denies access to the endpoint.

in this file:
`validator/src/Middleware/Validator.js :: handler()`

**Comment by thetutlage** [comment]
Can u point to the actual line?

**Comment by simontong** [comment]
From line 203 - 231. Below you can see its executing `_runValidations` first and then, if successful, it executes `_authorize`. So even if my form data is valid but I'm not authorized its going to send a bad response.

```js
async handle (ctx, next, validator) {
  validator = validator instanceof Array === true ? validator[0] : validator

  if (!validator) {
    throw new Error('Cannot validate request without a validator. Make sure to call Route.validator(\'validatorPath\')')
  }

  const validatorInstance = resolver.forDir('validators').resolve(validator)

  /**
   * Set request ctx on the validator
   */
  validatorInstance.ctx = ctx

  /**
   * Sanitize request data if there are sanitization rules
   */
  this._sanitizeData(ctx.request, validatorInstance)

  /**
   * Validate the request. This method should handle the request
   * response, since the middleware chain has been stopped.
   *
   * If this method doesn't handles the response, then a generic
   * response is made
   *
   * @type {void}
   */
  const validate = await this._runValidations(ctx.request, validatorInstance)
  if (!validate) {
    this._endResponseIfCan(ctx.response, 'Validation failed. Make sure to handle it inside validator.fails method', 400)
    return
  }

  /**
   * Authorize the request. This method should return true to
   * authorize the request.
   *
   * Make response or throw an exception to reject the request.
   *
   * Returning false from the method will result in a generic
   * error message
   */
  const authorized = await this._authorize(validatorInstance)
  if (!authorized) {
    this._endResponseIfCan(ctx.response, 'Unauthorized request. Make sure to handle it inside validator.authorize method', 401)
    return
  }

  /**
   * All good, so continue
   */
  await next()
}
```

**Comment by thetutlage** [comment]
There's also a `if` block there, which says right away of unable to `validate`

**Comment by simontong** [comment]
If current user posts data that passes validation but is unauthorized to access the endpoint the code will still run all the validation checks first then reject him.

**Comment by thetutlage** [comment]
This is how it is structured that validations runs and authorisation is next 

If the data submitted by the user is invalid then there is no point finding who they are

Maybe you want different behaviour in that case simply don’t use the authorization method and create your own middleware, that runs before the validator

**Comment by thetutlage** [comment]
Closing since not actionable

**Comment by HapLifeMan** [comment]
Hi Virk, this would be a great change, I think that's a better way to check if the user is authorized to perform the action before running validation rules.

I'm very confused because I come from Laravel, and Laravel runs the authorize method before running the rules... If you want to follow what they do (as you mostly did), this is the way to do it well 😉
