### ISSUE TITLE
Proposition to extend framework "request" instance with validate method

### ISSUE THREAD

**Issue by yariksav** [adonisjs/adonis-validation-provider#27]
It would be great to extend framework "request" instance in validation provider for same possibility as has laravel 5.5 framework
```
$validatedData = $request->validate([
        'title' => 'required|unique:posts|max:255',
        'body' => 'required'
    ]);
```

```
async request.validate({
    title: 'required|unique:posts|max:255',
    body: 'required'
})
```

>  If the validation rules pass, your code will keep executing normally; however, if validation fails, an exception will be thrown and the proper error response will automatically be sent back to the user. In the case of a traditional HTTP request, a redirect response will be generated, while a JSON response will be sent for AJAX requests.

it would make validation more simply than:

```
const { validate } = use('Validator')

class UserController {

  async store ({ request, session, response }) {
    const rules = {
      email: 'required|email|unique:users,email',
      password: 'required'
    }

    const validation = await validate(request.all(), rules)

    if (validation.fails()) {
      session
        .withErrors(validation.messages())
        .flashExcept(['password'])

      return response.redirect('back')
    }
```

**Comment by yariksav** [comment]
something like:
```
requestInstance.validation = (rules) => {
  let validation = await validateAll(this.all(), rules)
  if (validation.fails()) {
     throw new ValidationException(validation.messages())
  }
} 
```

**Comment by yariksav** [comment]
i added this to kernel.js and this works! But maybe this would be better to add directly to ValitationProvider

```
const { validateAll } = use('Validator')
const Request = use('Adonis/Src/Request')
const CE = use('@adonisjs/validator/src/Exceptions')

Request.macro('validate', async function (rules) {
  let validation = await validateAll(this.all(), rules)
  if (validation.fails()) {
    throw CE.ValidationException.validationFailed(validation.messages())
  }
})
```

use:
```
    await request.validate({
      name: 'min:5',
      status: 'in:A,D'
    })

```

**Comment by thetutlage** [comment]
I suggest using Route validators for that.

**Comment by yariksav** [comment]
Did you mean route middleware 'validation'? Yes, I used this, but for each action need to create own class file... This method seems to be much easier... especially for Rest API 
I made RequestValidationProvider for this, but it will be great to have this logic by core... like has Laravel 5.5, it is very useful

**Comment by thetutlage** [comment]
So design goals of Laravel and Adonis will not be same always, I believe adding too many ways to do one thing leads to confused decisions.

Also we as human beings have our own style of doing things ( no one superior over others ). 

So I suggest using the macro as you did in your project. Also you can share it with others by wrapping it inside a package and people who prefer your way will surely use it.

**Comment by yariksav** [comment]
https://github.com/yariksav/adonis-request-validation
