### ISSUE TITLE
Putting custom messages in locales files

### ISSUE THREAD

**Issue by mtamadon** [adonisjs/adonis-validation-provider#30]
I think in mvc model (when we have edge views) validation messages is more related to views (front end ) than backend (controller) + some times we need separate validation message for each language .

So I think ability to set custom messages in locales files will be good  (Laravel has this feature too. we can set messages on lang(locales) files & also controller)
Thank you.

**Comment by thetutlage** [comment]
I am not chasing Laravel features or building a Laravel clone.

Happy to hear more thoughts when they have technical advantages over ( Laravel does this )

**Comment by mtamadon** [comment]
@thetutlage : But laravel was only an example ..., I wrote two technical reason for that.
If it is not possible to add this to adonisjs (maybe because of time or other reasons ) Could you please tell me the way that I can do this?(I we really need this in our team)
Thanks.
