### ISSUE TITLE
validator for resource not working

### ISSUE THREAD

**Issue by fernandolguevara** [adonisjs/adonis-validation-provider#31]
my route configuration
 
```javascript
    Route
        .resource('products/categories', 'ProductCategoryController')
        .validator(new Map([
            ['products/categories.store', 'StoreProductCategory']
        ]))
        .apiOnly()
```

the validation no work, any suggestions?

**Comment by thetutlage** [comment]
Do u get any exceptions?

**Comment by fernandolguevara** [comment]
@thetutlage no, there is no exception, only a redirection to / route

**Comment by thetutlage** [comment]
With your code in place, I can see that validator has been applied. Can u double check by running `adonis route:list` command?

<img width="1007" alt="screen shot 2018-01-06 at 4 53 47 pm" src="https://user-images.githubusercontent.com/1706381/34639237-41503456-f302-11e7-859c-a52cdf4df7b2.png">

Notice `av:StoreProductCategory`

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well

**Comment by sujai1009** [comment]
hi thetutlage validator is not working for resource routing. In the route listing all info except the validators are shown
