### ISSUE TITLE
After sanitizor, object not changed

### ISSUE THREAD

**Issue by dimensi** [adonisjs/adonis-validation-provider#32]
Set on route validation. 
```
Route
  .post('/registration', 'UserController.startCreate')
  .validator('CreateUser')
```
Set sanitizor rules. 
```
  get sanitizationRules () {
    return {
      tel: 'format_tel'
    }
  }
```
After sanitization and success validation i get not mutated object. Why?

**Comment by RomainLanz** [comment]
Hey @edDimensi! 👋 

Where did you get the `format_tel` rules for sanitization?

**Comment by dimensi** [comment]
Hi! Here
```
const phone = require('phone')
const { hooks } = require('@adonisjs/ignitor')

hooks.after.providersBooted(() => {
  const Validator = use('Validator')

  const formatTel = (value, options) => {
    return phone(value, 'RUS')[0]
  }

  Validator.sanitizor.extend('formatTel', formatTel)
})

```

**Comment by RomainLanz** [comment]
You have registered the rule `formatTel` but you are using the rule `format_tel`.
May you change it and try again?

**Comment by dimensi** [comment]
formatTel work nice.
And in docs 
```
Extending Schema Validator
Extending Schema validator will register your custom rule to validations store and should follow defined convention, where all rules are registered as camelCase and consumed as snake_case.

For example, indicative’s alpha_numeric rule is defined as alphaNumeric inside validation store.
```

**Comment by RomainLanz** [comment]
Yes, but you aren't extending the validator here. You are extending the Sanitizer Service. 😄

**Comment by dimensi** [comment]
I change on camelCase, nothing change.
```
  get sanitizationRules () {
    return {
      tel: 'formatTel'
    }
  }
```
```
hooks.after.providersBooted(() => {
  const { sanitizor } = use('Validator')

  const formatTel = (value, options) => {
    return phone(value, 'RUS')[0]
  }

  sanitizor.extend('formatTel', formatTel)
})
```
Object in response:
```
{ tel: '+7 (999) 999-99-99',}
```
my function return `+79999999999`

**Comment by dimensi** [comment]
Hello?

**Comment by RomainLanz** [comment]
I don't get why you have changed your code?

**Comment by dimensi** [comment]
What? What me do? sanitizor rules not updated object, but if i use sanitizor direct it will be return new object.

**Comment by dimensi** [comment]
@RomainLanz I found where to find the bug! I used `request.post ()` to get the data I needed from the form. Then, as the validator mutates the response `response._all` object, and the response.post () method returns the `response.body`

https://github.com/adonisjs/adonis-validation-provider/blob/e701d81da2f6a66a1fedfb48bc24664070975f81/src/Middleware/Validator.js#L55-L62

Here create new object.
https://github.com/adonisjs/adonis-framework/blob/f255f1f16fdb9e82c96b69aaff1adc1a00c87a85/src/Request/index.js#L137-L140
But `response.post()` return old object
https://github.com/adonisjs/adonis-framework/blob/f255f1f16fdb9e82c96b69aaff1adc1a00c87a85/src/Request/index.js#L197-L199

**Comment by thetutlage** [comment]
@edDimensi Couple of things

1. Is `formatTel` method is being called at all?
2. Is `request.post()` only returns the wrong data or is it same with `request.all()`

**Comment by dimensi** [comment]
@thetutlage 
1. yes, it's work.
2. yes, only `.post()` wrong data. Because validator mutated ._all object, not body. 
In Request class you merge `this._body` with `this.get()` and on `request.all() => this._all`, validator mutated this object, but not mutated this.body.

**Comment by thetutlage** [comment]
Sure I’ll look into it, for now I can suggest to use the `all` method

**Comment by dimensi** [comment]
Yeah, i used it for avoid bug. But i lost on this 4 hours, because i think it's my mistake.
