### ISSUE TITLE
Bug to class name

### ISSUE THREAD

**Issue by danielsalles** [adonisjs/adonis-validation-provider#40]
If create `validator` using `path` the `class` name bug.

Example:
`adonis make:validator User/index`

Output:
```js
'use strict'

class User&#x2F;index {
  get rules () {
    return {
      // validation rules
    }
  }
}

module.exports = User&#x2F;index

```

**Comment by alanaasmaa** [comment]
I have same issue.

Did you get the validator to work in sub folder ?

**Comment by thetutlage** [comment]
It shouldn’t stop u from using it, simply put the class name manually.

Also I’ll fix the cli to produce the right class name

**Comment by alanaasmaa** [comment]
@thetutlage Damn u reply fast.

I tried to fix class name manually but it did not work. I get 204 No Content from my api.

**Comment by thetutlage** [comment]
204 is not an error, also response code is not a way to find if something works or not.

Make sure your controller does return something or calls `response.send`

**Comment by RomainLanz** [comment]
Issue moved to [adonisjs/adonis-cli #111](https://github.com/adonisjs/adonis-cli/issues/111) via [**ZenHub**](https://www.zenhub.com/)
