### ISSUE TITLE
This is down can't install

### ISSUE THREAD

**Issue by codingphasedotcom** [adonisjs/adonis-validation-provider#45]
![screen shot 2018-03-21 at 12 54 16 pm](https://user-images.githubusercontent.com/26421899/37724716-c7090728-2d07-11e8-8188-7c630ebeaeef.png)
I tried using adonis install @adonisjs/validator
and can't download even with npm or yarn

**Comment by RomainLanz** [comment]
Hey @codingphasedotcom! 👋 

You are installing using the scope **@adonis** instead of **@adonisjs**.

**Comment by codingphasedotcom** [comment]
wow

**Comment by thetutlage** [comment]
Closing, since the issue is fixed
