### ISSUE TITLE
Use a validator from a provider

### ISSUE THREAD

**Issue by franciscosucre** [adonisjs/adonis-validation-provider#48]
Hi, i have a set of base validators in a provider and i want to use them as a route validator.

I add the singleton in the provider like this:

```js
 this.app.singleton('Nuviio/Validators/UserOwnedListValidator', () => {
      return require('./Validators/UserOwnedListValidator')
    })
```

And i try to call it in a controller like this.

```js
Route.get('/', 'Api/CampaignController.list')
    .middleware([
      'logRequest',
      'auth:jwt',
      'userIsActive',
      'processQueryParams'
    ]).validator(['Nuviio/Validators/UserOwnedListValidator'])
```

It always gives me a module_not_found error. Please help.

**Comment by thetutlage** [comment]
Yup, since it is looking for the validator inside the conventional directory, `app/Validators`. You can tell the resolver to pull a binding from the IoC container as follows.

```js
validator('@provider:Nuviio/Validators/UserOwnedListValidator')
```

**Comment by RomainLanz** [comment]
Closing since answered and no response from issue reporter.
