### ISSUE TITLE
Number validation fail without sanitize

### ISSUE THREAD

**Issue by jmlaya** [adonisjs/adonis-validation-provider#50]
I have a field with a float (money) value. I tried to apply `number` validation, but it fails because the value retrieved is a string. Works fine using `to_int` sanitizer, but in this case, I need a `to_number` or `to_float` sanitizer.

**Comment by tomcss** [comment]
I've run into the same problem.

**Comment by thetutlage** [comment]
I believe you can extend the sanitizer and add your own `to_float` rule.

**Comment by thetutlage** [comment]
Closing since not actionable
