### ISSUE TITLE
validation.fails() always return true

### ISSUE THREAD

**Issue by annymosse** [adonisjs/adonis-validation-provider#52]
hi , i have the latest version for now `@adonisjs/vlidator` v5.0.3, and i copied the same example in the docs ,but always return true the ,and if there is an ability to check all the request inputs and return single json response have the checks for all the inputs , coz now the validator in each request check the first input if have error return without continue the next inputs
**thanks**

**Comment by RomainLanz** [comment]
Hey @annymosse ! 👋 

Could you please provide some code to replicate?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
