### ISSUE TITLE
Email Validation for rule 'email' fails

### ISSUE THREAD

**Issue by bhavikgarg** [adonisjs/adonis-validation-provider#54]
I am facing an issue in email validation. While trying to validate emails, I always get this error 
` [ { message: 'e.hasOwnProperty is not a function',
   field: 'email',
   validation: 'ENGINE_EXCEPTION' } ]`

I am unable to reproduce the cause and also checked the NPM package, but could not get insights.

**Comment by thetutlage** [comment]
Share some code please

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
