### ISSUE TITLE
Bug to class name

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/adonis-validation-provider#56]
_From @RomainLanz on June 8, 2018 21:50_

@danielsalles commented on [Mon Feb 19 2018](https://github.com/adonisjs/adonis-validation-provider/issues/40)

If create `validator` using `path` the `class` name bug.

Example:
`adonis make:validator User/index`

Output:
```js
'use strict'

class User&#x2F;index {
  get rules () {
    return {
      // validation rules
    }
  }
}

module.exports = User&#x2F;index

```

---

@alanaasmaa commented on [Sat Mar 24 2018](https://github.com/adonisjs/adonis-validation-provider/issues/40#issuecomment-375889274)

I have same issue.

Did you get the validator to work in sub folder ? 

---

@thetutlage commented on [Sat Mar 24 2018](https://github.com/adonisjs/adonis-validation-provider/issues/40#issuecomment-375890989)

It shouldn’t stop u from using it, simply put the class name manually.

Also I’ll fix the cli to produce the right class name

---

@alanaasmaa commented on [Sat Mar 24 2018](https://github.com/adonisjs/adonis-validation-provider/issues/40#issuecomment-375891180)

@thetutlage Damn u reply fast.

I tried to fix class name manually but it did not work. I get 204 No Content from my api.

---

@thetutlage commented on [Sat Mar 24 2018](https://github.com/adonisjs/adonis-validation-provider/issues/40#issuecomment-375892035)

204 is not an error, also response code is not a way to find if something works or not.

Make sure your controller does return something or calls `response.send`

_Copied from original issue: adonisjs/adonis-cli#111_

**Comment by thetutlage** [comment]
The validator is generated via `adonis-validation-provider` and hence moving issue to that repo

**Comment by trantuan94** [comment]
I installed your package into my Adonisjs project and also tried to generate Validator file by your command. But I still detect this bug. The 'adonis make:validator  User/CreateUser' command create the new file in ./Validators/User/CreateUser.js but the 'class name' still invalid 'UserCreateUser'.
