### ISSUE TITLE
How to extend validator?

### ISSUE THREAD

**Issue by Ali-Azmoud** [adonisjs/adonis-validation-provider#58]
Hi
I know this is somehow mentioned in the documentations but it's not documented well !
I've read all docs of current version of Adonis ( 4.1 ) and ( 4.0 ) and also ( 3.2 ). I couldn't find out how to extend it.
I want to add `exists` to my validator.
There are a bunch of code in the documentation which is not clear WHERE should I paste them and HOW to autoload them or whatever.
Can somebody please make it more clear or any example

**Comment by RomainLanz** [comment]
Hey @Ali-Azmoud! 👋 

To extends to Validator Provider you need to add code to the `start/hooks.js` (create it if it doesn't exist).

Then add the code you have here https://adonisjs.com/docs/4.1/validator#_extending_validator.

**Comment by begueradj** [comment]
Hello @Ali-Azmoud 
You can write that code directly in `start/hooks.js` file. I did this some weeks ago.
If you are still confused, I can write an article with a naive demo on my blog (no commercial things on my blog, just want to help)

**Comment by sifloz** [comment]
I'm still confused.
I tried to do what @RomainLanz mentioned above but I just cannot figure it out.
I created the `start/hook.js` file and then pasted directly the code from Documentation without anything else and now it no longer works.

I'm quite new with AdonisJS and I think this should be clearer in the documentation.
I'd really appreciate your help @begueradj

**Comment by begueradj** [comment]
Feel free to ask your questions on https://forum.adonisjs.com/ @sifloz

**Comment by hiukky** [comment]
I have the same problem creating a custom rule following the tutorial of site.

**Comment by jstavanja** [comment]
If anyone is still wondering how to do this, I found a solution.

Create the `start/hooks.js` file (if it does not yet exist). Then, copy the code sample for adding the "exist" validation rule to the Validator instance from the [AdonisJS documentation](https://adonisjs.com/docs/4.1/validator#_extending_validator) and paste it inside this block of code:

```javascript
const { hooks } = require('@adonisjs/ignitor')

hooks.after.providersBooted(() => {
    // paste code here
})
```

This way, the use('Validator') function call won't fail and your exist validation rule will be available to use throughout the application.

**Comment by enbermudas** [comment]
I've used the @jstavanja answer but it's throwing the next error:

```
Application crashed, make sure to kill all related running process, fix the issue and re-run the app
changed start/hooks.js

Error: Cannot find module 'Validator'
Require stack:
- /home/kike/prs/projects/rpbb/node_modules/require-stack/src/index.js
- /home/kike/prs/projects/rpbb/node_modules/require-stack/index.js
- /home/kike/prs/projects/rpbb/node_modules/@adonisjs/fold/src/Ioc/index.js
- /home/kike/prs/projects/rpbb/node_modules/@adonisjs/fold/index.js
- /home/kike/prs/projects/rpbb/server.js
```

My code:

```
'use strict';

const Validator = use('Validator');
const Database = use('Database');
const { hooks } = require('@adonisjs/ignitor');

hooks.after.providersBooted(() => {
  const existsFn = async (data, field, message, args, get) => {
    const value = get(data, field);
    if (!value) {
      return;
    }

    const [table, column] = args;
    const row = await Database.table(table).where(column, value).first();

    if (!row) {
      throw message;
    }
  };

  Validator.extend('exists', existsFn);
});
```

**Comment by jstavanja** [comment]
> I've used the @jstavanja answer but it's throwing the next error:
> 
> ```
> Application crashed, make sure to kill all related running process, fix the issue and re-run the app
> changed start/hooks.js
> 
> Error: Cannot find module 'Validator'
> Require stack:
> - /home/kike/prs/projects/rpbb/node_modules/require-stack/src/index.js
> - /home/kike/prs/projects/rpbb/node_modules/require-stack/index.js
> - /home/kike/prs/projects/rpbb/node_modules/@adonisjs/fold/src/Ioc/index.js
> - /home/kike/prs/projects/rpbb/node_modules/@adonisjs/fold/index.js
> - /home/kike/prs/projects/rpbb/server.js
> ```

Make sure that you add the use('Validator') "import" inside the hooks.after.providersBooted( () => ...) callback. Before the providers are booted, the Validator might not yet be instantiated. Same goes for any other use statements (not the hooks require one though).

**Comment by FeMaffezzolli** [comment]
> If anyone is still wondering how to do this, I found a solution.
> 
> Create the `start/hooks.js` file (if it does not yet exist). Then, copy the code sample for adding the "exist" validation rule to the Validator instance from the [AdonisJS documentation](https://adonisjs.com/docs/4.1/validator#_extending_validator) and paste it inside this block of code:
> 
> ```js
> const { hooks } = require('@adonisjs/ignitor')
> 
> hooks.after.providersBooted(() => {
>     // paste code here
> })
> ```
> 
> This way, the use('Validator') function call won't fail and your exist validation rule will be available to use throughout the application.

This works fine for me. Thanks! 👊
