### ISSUE TITLE
Describing validators

### ISSUE THREAD

**Issue by artem-a** [adonisjs/adonis-validation-provider#59]
Hi,is it possible to describe the validator once (as class or object) and use it in different places: ace commands, controller or as middleware?

**Comment by thetutlage** [comment]
Validators are tied to the routes and they have extra behaviour which is specific for HTTP requests. For example: 

When validation fails, the validator will redirect the user back and flash the errors inside session flash messages, and ofcourse it's not possible to redirect anywhere in case of `ace` commands.

If you want a generic validation helper, then create your own class and use it anywhere you want.


**app/Services/UserValidator.js**
```js
class UserValidator {
   async validate () {
      // run validations here
   }
}
```

And then use the above class anywhere you want
