### ISSUE TITLE
[Feature Request] include request.validated() to get all valid fields from request

### ISSUE THREAD

**Issue by kieuminhcanh** [adonisjs/adonis-validation-provider#61]
# Why this feature is required (specific use-cases will be appreciated)?
I use Route validator. And I only want get valid fields. Other fields do not define in Rules will be remove.

**UserStore.js**
```javascript
class UserStore {
  get rules() {
    return {
      username: "required|unique:users",
      email: "required|email|unique:users",
      password: "required"
    };
  }
}
```

**UserController.js**
```javascript
async store({ request, response }) {
    $input = request.only(['username','email','password']);
   // In laravel, just need: $input = $request->validated();
   // I needn't repeat again above step
    const user = await User.create($input)
}
```
I thing this feature will help faster's code and security because all data alway valid. Before use in controller.

**Comment by RomainLanz** [comment]
Hey @canhkieu! 👋 

This feature is already planned to be added in the next release.

**Comment by thetutlage** [comment]
The newer release targeting v5 will fix this issue. The `request.validate` method will right an object of only validated properties.
