### ISSUE TITLE
Allow to define snake_case rules name in Validator.extend()

### ISSUE THREAD

**Issue by HapLifeMan** [adonisjs/adonis-validation-provider#62]
## Why this feature is "required"?
We are using rules in strings like this: `required_with:otherField`, and when we want to extend the validator with custom rules, we are obliged to define them in `camelCase`.

That can be a good _feature_ to be able to define them in `snake_case` too, in order to be more consistent with Indicative :)

Use case: when searching for a custom rule in your IDE, it's super effective to find their definition and usage with the same case/search.

As I can see in this package, it can be done with a `snake_case` to `camelCase` converter right here (then add one test and you'll be good ✨):
https://github.com/adonisjs/adonis-validation-provider/blob/2466338ee147c4402a7a2822e8cfaad12676c2f7/src/Validator/index.js#L26

(PS: I was ready to make a PR but I'm pretty sure you will integrate it better than me 😊)

**Comment by thetutlage** [comment]
Though it's an easy task, I will skip it for now. However, if you are interested, you can create a PR for same in the https://github.com/poppinss/indicative repo

**Comment by thetutlage** [comment]
Also closing, feel free to re-open, if you plan to add a PR
