### ISSUE TITLE
Ability to use both syntax styles in same rule

### ISSUE THREAD

**Issue by derrikfleming** [adonisjs/adonis-validation-provider#64]
## Why this feature is required (specific use-cases will be appreciated)?
I'm attempting to use multiple Validators (required, unique) in congruence with a custom RegEx expression, like so:

```
const rules = {
      mac_address:[ 'required', 'unique:units,mac_address', rule('regex', new RegExp('^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'))],
    }
```

However, in the above `rules` only the RegEx is actually validated. The others don't work unless I remove the RegEx rule.

## Have you tried any other work arounds?
I've poked around a little bit with the above, but was unable to come up with a solution on my own. I've created a question on the Forum in Help>Validator [here](https://forum.adonisjs.com/t/how-do-i-combine-custom-regex-rule-and-built-in-indicative-validators/3582).
Someone on the Discord suggested creating extending Validator. This worked, but what I was originally attempting still seems favorable.
I spent more time looking around on the Forum for similar questions, but I wasn't able to find anything, though it could have been my search terms.

## Are you willing to work on it with little guidance?
I could try, but my confidence level is not high in regards to myself working on this alone.

**Comment by thetutlage** [comment]
Not valid with the newer API targeting the framework v5.
