### ISSUE TITLE
The class name invalid when generate Validator file using command

### ISSUE THREAD

**Issue by trantuan94** [adonisjs/adonis-validation-provider#65]
## Package version

v5.0.9
## Node.js and npm version

Node v10.16.0
npm v6.9.0
OS: Ubuntu 18.04 LTS
## Description
I installed your package into my Adonisjs project and also tried to generate Validator file by your command. But I still detect this bug. The 'adonis make:validator  User/CreateUser' command create the new file in ./Validators/User/CreateUser.js but the 'class name' still invalid -UserCreateUser.

**Comment by RomainLanz** [comment]
Hey @trantuan94! 👋 

Since this code is tested in our package could you please make a falling test so we can reproduce the issue?

**Comment by thetutlage** [comment]
Closing since it not valid anymore
