### ISSUE TITLE
Indicative version upgrade dependency

### ISSUE THREAD

**Issue by FrancoisXavierNoe** [adonisjs/adonis-validation-provider#68]
## Why this feature is required (specific use-cases will be appreciated)?
I would like to use the new features present in Indicative v7.2.0 but @adonisjs/validator v5.0.6 have an old dependency : "indicative": "^5.0.8"

## Have you tried any other work arounds?
No

## Are you willing to work on it with little guidance?
It depends of the work...

**Comment by pdipax** [comment]
please update the dependency. Thanks

**Comment by RomainLanz** [comment]
If you cannot wait for the update we will happily accept a PR. 🙂

**Comment by gap777** [comment]
@RomainLanz  Can you provide an estimate of when you  would otherwise get to upgrading this dep?

As far as the PR from @pdipasqua (or myself, or anyone else for that matter) goes... @RomainLanz do you foresee this as a very difficult upgrade?

**Comment by thetutlage** [comment]
Not relevant with the newer release. Since, we are not using Indicative anymore. 

Docs will be out with the newer release of AdonisJS.
