### ISSUE TITLE
validator@5.0.6 replaced form fields to uploaded files

### ISSUE THREAD

**Issue by b01110011** [adonisjs/adonis-validation-provider#78]
## Package version
@adonisjs/validator@5.0.6

## Node.js and npm version
Node.js v12.16.0
npm 6.13.4

## Sample Code (to reproduce the issue)
I send data by method "multipart/form-data", after processing bodyparser in the output, I get 2 objects:
1) request.body - with form fields
2) request._files - with uploaded files
Like this:
```
request.body {
  path: 'qwe-123',
  name: '1234567890',
  apartment_layout: [ { area: 'qewer', type: 'rqwer' } ]
}
request._files {
  photo: File {...},
  apartment_layout: [ { image: [File] } ]
}
```

At the time of validation, these 2 objects are merging with such result:
```
data {
  path: 'qwe-123',
  name: '1234567890',
  photo: File {...},
  apartment_layout: [ { image: [File] } ]
}
```
and apartment_layout was supposed to be
`apartment_layout: [ { area: 'qewer', type: 'rqwer', image: [File] } ]`

@Adonisjs\validator\src\Middleware\Validator.js  line 112
```
if (!data) {
      const files = typeof (request.files) === 'function' ? request.files() : {}
      data = Object.assign({}, request.all(), files)
    }
```
Object.assign replaced my fields data to files data
_____________________________________________________
You need replace
`data = Object.assign({}, request.all(), files)`
to
`data = _.merge(request.all(), files)`

**Comment by thetutlage** [comment]
Please format the codeblocks 🙏

**Comment by b01110011** [comment]
Sorry, I forget about it :grinning:

**Comment by b01110011** [comment]
Need replace on it
`data = _.merge({}, request.all(), files)`

because object request.all() too merges, its wrong
