### ISSUE TITLE
Adding 'true' and 'false' strings to BOOLEAN values

### ISSUE THREAD

**Issue by Dolu89** [adonisjs/adonis-validation-provider#86]
I need to have 'true' and 'false' values in :
const BOOLEAN_POSITIVES = [ '1', 1, 'on', 'true' ]
const BOOLEAN_NEGATIVES = [ '0', 0, 'off', 'false' ]

## Why this feature is required (specific use-cases will be appreciated)?
It should be added because edge template receive 'true' or 'false' as value when doing this :
Controller.ts
```
const myObjectWithBoolean = await MyObjectWithBoolean.query()....firstOrFail() //{myBoolean: true}
return view.render('myView', {...myObjectWithBoolean.toJSON()})
```

view.edge
`<p>{{myBoolean}}</p>  => display 'true', not 1, '1' or 'on'`

eg.
```
<div x-data="{ showMessage: {{show_message}} }">
  <input type="checkbox" x-model="showMessage">
  <input type="hidden" name="showMessage" :value="showMessage">
</div>
```

## Have you tried any other work arounds?
No, I'm using {{myBoolean}} in alpine.js x-data to get a boolean value

## Are you willing to work on it with little guidance?
Yes

**Comment by thetutlage** [comment]
Mind sharing a PR for same?

**Comment by Dolu89** [comment]
Pull request sent https://github.com/adonisjs/validator/pull/87

**Comment by thetutlage** [comment]
Fixed
