### ISSUE TITLE
rules.Range() does not work

### ISSUE THREAD

**Issue by fnoquiq** [adonisjs/adonis-validation-provider#88]
When using the following code: `schema.number([rules.range(10, 100)])`, an error appears.

The error: `Property 'range' does not exist on type 'Rules'.ts(2339)`.

I'm following the same tutorial on the site -> https://preview.adonisjs.com/guides/validator/schema-types

![Captura de Tela 2020-07-07 às 15 30 18](https://user-images.githubusercontent.com/11557379/86826207-ca36af00-c066-11ea-9bde-1dfc324a0a3a.png)

## Package version

```json
{
    "@adonisjs/ace": "^6.0.0",
    "@adonisjs/auth": "^4.2.4",
    "@adonisjs/core": "^5.0.0-preview-rc",
    "@adonisjs/fold": "^6.0.0",
    "@adonisjs/lucid": "^8.2.2",
}
```

## Node.js and npm version
`Nodejs: 12.18.2`
`Npm: 6.14.5`
`Yarn: 1.22.4`

## Sample Code (to reproduce the issue)
```ts
import { HttpContextContract } from '@ioc:Adonis/Core/HttpContext'
import { schema, rules } from '@ioc:Adonis/Core/Validator'

export default class StoreValidator {
  constructor(private ctx: HttpContextContract) { }

  public schema = schema.create({
    testNumber: schema.number([rules.unsigned(), rules.range(10, 100)])
  })

  public cacheKey = this.ctx.routeKey

  public messages = {}
}
```

## BONUS (a sample repo to reproduce the issue)

Sample repo -> https://github.com/fnoquiq/adonis-validator-issue-range-example

**Comment by thetutlage** [comment]
Thanks for reporting. Seems to be missing

**Comment by Xstoudi** [comment]
Can I make a PR? @thetutlage

**Comment by thetutlage** [comment]
Sure, feel free to do that. I will release it right away

**Comment by Xstoudi** [comment]
Here it is @thetutlage #89 :)
