### ISSUE TITLE
Unique validation while update

### ISSUE THREAD

**Issue by subhamcodes** [adonisjs/adonis-validation-provider#91]
"@adonisjs/core": "^5.0.0-preview-rc"

There is no description regarding the unique rule. I want to check for unique fields while updating.

schema.create({
  email: schema.string({}, [
    rules.email(),
    rules.unique({ table: 'users', column: 'email' })
  ])
})

**Comment by thetutlage** [comment]
Shouldn't be an issue. Please open [discussion threads](https://github.com/adonisjs/core/discussions) for these sort of things and please format your code examples.
