### ISSUE TITLE
Validating plain text ends up in a strange way.

### ISSUE THREAD

**Issue by Xstoudi** [adonisjs/adonis-validation-provider#99]
## Explanation
When a JSON string with a bad content-type header is sent for validation in POST method body, it ends up really strange. I think plaintext header should be rejected without even running the validation on it.

For the following body:
```
{
    "page": "/home",
    "hostname": "localhost:5000"
}
```

Currently, I get back a 422 error (unprocessable entity) with the following response body:
```
{
   "errors":[
      {
         "rule":"required",
         "field":"page",
         "message":"required validation failed"
      },
      {
         "rule":"required",
         "field":"page",
         "message":"required validation failed"
      },
      {
         "rule":"required",
         "field":"hostname",
         "message":"required validation failed"
      },
      {
         "rule":"required",
         "field":"hostname",
         "message":"required validation failed"
      }
   ]
}
```

## Package version
7.4.1

## Node.js and npm version
Node.js:  v14.0.0
Npm: 6.14.4

## Sample Code (to reproduce the issue)
```ts
  public schema = schema.create({
    page: schema.string({ escape: true, trim: true }, [rules.maxLength(500), rules.required()]),
    hostname: schema.string({escape: true, trim: true }, [rules.required()])
  })
```

**Comment by thetutlage** [comment]
I believe, the validator is behaving the right way. It shouldn't worry about the HTTP specifics and malformed headers. If we want we can use bodyparser to check for this.

**Comment by Xstoudi** [comment]
Got it. One more question, is this a reason to expose isRequired rule while schema types are required by default?
Found out after hours that it was what caused `required` errors to be duplicated.

**Comment by thetutlage** [comment]
@Xstoudi Yeah, we can remove the required rule from the set of the rules.

**Comment by thetutlage** [comment]
For now, I will close the issue, since it there is nothing to act on
